# --- 1. ClusterSecretStore (Vault-provider) ---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store                  # Byt namn så vi inte krockar med gamla mock
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"   # Vault-serverns URL inom k8s
      path: "secret"                                        # Bas-path i Vault där secrets ligger
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token                                 # Namnet på k8s-secreten med token
          key: token                                        # Nyckeln i k8s-secreten som innehåller token
          namespace: external-secrets    # Token i external-secrets

---
# --- 2. ExternalSecret (måste ligga i default för att skapa secret där) ---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-api-key
  namespace: default                  # VIKTIGT: samma som mål-secret
spec:
  secretStoreRef:
    name: vault-store  # Pekar på Vault-store. ClusterSecretStore används automatiskt
    kind: ClusterSecretStore
  target:
    name: app-secret           # Namnet på den skapade k8s-secreten
    creationPolicy: Owner
  data:
    - secretKey: API_KEY      # Nyckeln/miljövariabeln i den skapade k8s-secreten
      remoteRef:
        key: myapp            # Nyckeln/path i Vault
        property: api-key     # Den specifika propertyn i Vault-secret