# --- 1. ClusterSecretStore (Vault-provider) ---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store                  # Byt namn så vi inte krockar med gamla mock
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets    # Token i external-secrets

---
# --- 2. ExternalSecret (måste ligga i default för att skapa secret där) ---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-api-key
  namespace: default                  # VIKTIGT: samma som mål-secret
spec:
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: myapp
        property: api-key