# --- 1. Mock Secret ---
apiVersion: v1
kind: Secret
metadata:
  name: mock-api-key
  namespace: default
type: Opaque
data:
  API_KEY: dGVzdDEyMw==  # base64 för hemligt värde

---
# --- 2. ClusterSecretStore ---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: mock-store
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-public  
          key: ca.crt

---
# --- 3. ExternalSecret ---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-api-key
  namespace: default
spec:
  secretStoreRef:
    name: mock-store
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: mock-api-key
        property: API_KEY